from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings

# Create your models here.

class User(AbstractUser):
    ROLE_CHOICES = (
        ('admin', 'Admin'),
        ('user', 'User'),
    )
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='user')

class Question(models.Model):
    TYPE_CHOICES = (
        ("Multiple Choice", "Multiple Choice"),
        ("True/False", "True/False"),
        ("Short Answer", "Short Answer"),
    )
    SPECIALIZATION_CHOICES = (
        ("Software Engineering", "Software Engineering"),
        ("Network Engineering", "Network Engineering"),
        ("Cloud Computing", "Cloud Computing"),
        ("Cybersecurity", "Cybersecurity"),
        ("Data Science", "Data Science"),
    )

    question = models.TextField()
    type = models.CharField(max_length=50, choices=TYPE_CHOICES)
    specialization = models.CharField(max_length=100, choices=SPECIALIZATION_CHOICES)
    options = models.JSONField(null=True, blank=True, help_text="For multiple choice questions")
    answer = models.TextField()
    is_generated = models.BooleanField(default=False, help_text="True if generated by AI")
    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='created_questions'
    )

    def __str__(self):
        return self.question[:50] # Return first 50 chars of question

class UserStats(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='stats')
    exams_taken = models.IntegerField(default=0)
    total_questions_answered = models.IntegerField(default=0)
    correct_answers = models.IntegerField(default=0)

    def __str__(self):
        return f"Stats for {self.user.username}"

    @property
    def accuracy(self):
        if self.total_questions_answered == 0:
            return 0
        return (self.correct_answers / self.total_questions_answered) * 100

# Signal to create UserStats when a new User is created
@receiver(post_save, sender=User)
def create_user_stats(sender, instance, created, **kwargs):
    if created:
        UserStats.objects.create(user=instance)

# Signal to save UserStats when a new User is created
@receiver(post_save, sender=User)
def save_user_stats(sender, instance, **kwargs):
    # Check if the related UserStats object exists.
    # It might not if the user was created before this signal was implemented.
    if hasattr(instance, 'stats'):
        instance.stats.save()
    else:
        # If it doesn't exist, create it.
        UserStats.objects.create(user=instance)
